version: '3.1'

services:
  node:
    image: hw36-node:v1
    environment:
      BALANCER: "balanceruri"
    ports:
      - "18189:8189"
  loadbalancer:
    image: hw36-loadbalancer:v1
    ports:
      - "18191:8191"